package accesoDato;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private String nombreProveedor;
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

    public Compra() {
    }

	
    public Compra(Date fecha) {
        this.fecha = fecha;
    }
    public Compra(Date fecha, String nombreProveedor, Set<Detallecompra> detallecompras) {
       this.fecha = fecha;
       this.nombreProveedor = nombreProveedor;
       this.detallecompras = detallecompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }




}


