package accesoDato;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA



/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int id;
     private Venta venta;
     private Producto producto;
     private int preciounidad;
     private int cantidad;

    public Detalleventa() {
    }

    public Detalleventa(int id, Venta venta, Producto producto, int preciounidad, int cantidad) {
       this.id = id;
       this.venta = venta;
       this.producto = producto;
       this.preciounidad = preciounidad;
       this.cantidad = cantidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getPreciounidad() {
        return this.preciounidad;
    }
    
    public void setPreciounidad(int preciounidad) {
        this.preciounidad = preciounidad;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


