package accesoDato;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA



/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private int id;
     private Compra compra;
     private Producto producto;
     private int preciounidad;
     private int cantidad;

    public Detallecompra() {
    }

    public Detallecompra(int id, Compra compra, Producto producto, int preciounidad, int cantidad) {
       this.id = id;
       this.compra = compra;
       this.producto = producto;
       this.preciounidad = preciounidad;
       this.cantidad = cantidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getPreciounidad() {
        return this.preciounidad;
    }
    
    public void setPreciounidad(int preciounidad) {
        this.preciounidad = preciounidad;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


