package accesoDato;
// Generated 20-jun-2014 23:45:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int stock;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

    public Producto() {
    }

	
    public Producto(String nombre, int stock) {
        this.nombre = nombre;
        this.stock = stock;
    }
    public Producto(String nombre, int stock, Set<Detalleventa> detalleventas, Set<Detallecompra> detallecompras) {
       this.nombre = nombre;
       this.stock = stock;
       this.detalleventas = detalleventas;
       this.detallecompras = detallecompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }




}


